<?php


use Phinx\Seed\AbstractSeed;

class Cities extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run()
    {
        $table = $this->table('cities');

        $data = [
            [
                'id' => '1',
                'name' => 'Aceh Barat Daya',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '2',
                'name' => 'Aceh Besar',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '3',
                'name' => 'Agam',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '4',
                'name' => 'Ambon',
                'province_id' => '3',
                'created_by' => '1',
            ],
            [
                'id' => '5',
                'name' => 'Badung',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '6',
                'name' => 'Balikpapan',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '7',
                'name' => 'Banda Aceh',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '8',
                'name' => 'Bandung',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '9',
                'name' => 'Bangka',
                'province_id' => '7',
                'created_by' => '1',
            ],
            [
                'id' => '10',
                'name' => 'Bangka Barat',
                'province_id' => '7',
                'created_by' => '1',
            ],
            [
                'id' => '11',
                'name' => 'Bangka Selatan',
                'province_id' => '7',
                'created_by' => '1',
            ],
            [
                'id' => '12',
                'name' => 'Bangka Tengah',
                'province_id' => '7',
                'created_by' => '1',
            ],
            [
                'id' => '13',
                'name' => 'Bangkalan',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '14',
                'name' => 'Bangkinang Kota',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '15',
                'name' => 'Bangli',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '16',
                'name' => 'Banjar',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '17',
                'name' => 'Banjarmasin',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '18',
                'name' => 'BanjarNegara',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '19',
                'name' => 'Bantul',
                'province_id' => '12',
                'created_by' => '1',
            ],
            [
                'id' => '20',
                'name' => 'Banyumas',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '21',
                'name' => 'Banyuwangi',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '22',
                'name' => 'Batam',
                'province_id' => '13',
                'created_by' => '1',
            ],
            [
                'id' => '23',
                'name' => 'Batang',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '24',
                'name' => 'Batang Hari',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '25',
                'name' => 'Batu Bara',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '26',
                'name' => 'Batu sangkar',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '27',
                'name' => 'Bekasi',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '28',
                'name' => 'Bener Meriah',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '29',
                'name' => 'Bengkalis',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '30',
                'name' => 'Bengkayang',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '31',
                'name' => 'Bengkulu',
                'province_id' => '17',
                'created_by' => '1',
            ],
            [
                'id' => '32',
                'name' => 'Bengkulu selatan',
                'province_id' => '17',
                'created_by' => '1',
            ],
            [
                'id' => '33',
                'name' => 'Berau',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '34',
                'name' => 'Bima',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '35',
                'name' => 'Binjai',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '36',
                'name' => 'BINTAN',
                'province_id' => '13',
                'created_by' => '1',
            ],
            [
                'id' => '37',
                'name' => 'BIREUN',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '38',
                'name' => 'Blitar',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '39',
                'name' => 'Blora',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '40',
                'name' => 'Boalemo',
                'province_id' => '19',
                'created_by' => '1',
            ],
            [
                'id' => '41',
                'name' => 'Bogor',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '42',
                'name' => 'Bojonegoro',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '43',
                'name' => 'BONDOWOSO',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '44',
                'name' => 'Bone Bolango',
                'province_id' => '19',
                'created_by' => '1',
            ],
            [
                'id' => '45',
                'name' => 'Bontang',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '46',
                'name' => 'BOYOLALI',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '47',
                'name' => 'Brebes',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '48',
                'name' => 'Bukit Tinggi',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '49',
                'name' => 'BULELENG',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '50',
                'name' => 'CALANG',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '51',
                'name' => 'Ciamis',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '52',
                'name' => 'Cianjur',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '53',
                'name' => 'Cikampak, Labuhanbatu Selatan',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '54',
                'name' => 'CILACAP',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '55',
                'name' => 'Cilegon',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '56',
                'name' => 'Cirebon',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '57',
                'name' => 'Curup',
                'province_id' => '17',
                'created_by' => '1',
            ],
            [
                'id' => '58',
                'name' => 'Deli Serdang',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '59',
                'name' => 'DENPASAR',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '60',
                'name' => 'Depok',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '61',
                'name' => 'Dharmasraya',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '62',
                'name' => 'DOMPU',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '63',
                'name' => 'Duri',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '64',
                'name' => 'Garut',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '65',
                'name' => 'GIANYAR',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '66',
                'name' => 'Gorontalo',
                'province_id' => '19',
                'created_by' => '1',
            ],
            [
                'id' => '67',
                'name' => 'Gresik',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '68',
                'name' => 'Grobogan',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '69',
                'name' => 'Gunungkidul',
                'province_id' => '12',
                'created_by' => '1',
            ],
            [
                'id' => '70',
                'name' => 'Indramayu',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '71',
                'name' => 'Jakarta Barat',
                'province_id' => '21',
                'created_by' => '1',
            ],
            [
                'id' => '72',
                'name' => 'Jakarta Pusat',
                'province_id' => '21',
                'created_by' => '1',
            ],
            [
                'id' => '73',
                'name' => 'Jakarta Selatan',
                'province_id' => '21',
                'created_by' => '1',
            ],
            [
                'id' => '74',
                'name' => 'Jakarta Timur',
                'province_id' => '21',
                'created_by' => '1',
            ],
            [
                'id' => '75',
                'name' => 'Jakarta Utara',
                'province_id' => '21',
                'created_by' => '1',
            ],
            [
                'id' => '76',
                'name' => 'JAMBI',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '77',
                'name' => 'Jayapura',
                'province_id' => '22',
                'created_by' => '1',
            ],
            [
                'id' => '78',
                'name' => 'JEMBER SELATAN',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '79',
                'name' => 'JEMBER UTARA',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '80',
                'name' => 'JEMBRANA',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '81',
                'name' => 'Jepara',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '82',
                'name' => 'Jombang',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '83',
                'name' => 'Kampar',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '84',
                'name' => 'KARANGANYAR',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '85',
                'name' => 'KARANGASEM',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '86',
                'name' => 'karawang',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '87',
                'name' => 'KEBUMEN',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '88',
                'name' => 'Kediri',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '89',
                'name' => 'Kendari',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '90',
                'name' => 'KETAPANG',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '91',
                'name' => 'KLATEN',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '92',
                'name' => 'KLUNGKUNG',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '93',
                'name' => 'KOTA BIMA',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '94',
                'name' => 'Kota Binjai',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '95',
                'name' => 'Kota Pinang, Labuhanbatu Selatan',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '96',
                'name' => 'Kotamadya Lubuk Linggau',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '97',
                'name' => 'KUBU RAYA',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '98',
                'name' => 'Kudus',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '99',
                'name' => 'Kulonprogo',
                'province_id' => '12',
                'created_by' => '1',
            ],
            [
                'id' => '100',
                'name' => 'Kumpulan',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '101',
                'name' => 'Kuningan',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '102',
                'name' => 'Kupang',
                'province_id' => '25',
                'created_by' => '1',
            ],
            [
                'id' => '103',
                'name' => 'LABUAN',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '104',
                'name' => 'Labuhan batu',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '105',
                'name' => 'Labuhan batu selatan',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '106',
                'name' => 'Labuhan batu Utara',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '107',
                'name' => 'Lahat',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '108',
                'name' => 'Lamongan',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '109',
                'name' => 'LAMPUNG',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '110',
                'name' => 'LAMPUNG SELATAN',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '111',
                'name' => 'LAMPUNG TENGAH',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '112',
                'name' => 'LAMPUNG TIMUR',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '113',
                'name' => 'LAMPUNG UTARA',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '114',
                'name' => 'LANDAK',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '115',
                'name' => 'Langkat',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '116',
                'name' => 'LHOKSEUMAWE',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '117',
                'name' => 'LIPAT KAIN',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '118',
                'name' => 'LOMBOK TENGAH',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '119',
                'name' => 'LOMBOK BARAT',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '120',
                'name' => 'LOMBOK TIMUR',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '121',
                'name' => 'LOMBOK UTARA',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '122',
                'name' => 'Lubuk Lingau',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '123',
                'name' => 'Lubuk Sikaping',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '124',
                'name' => 'LUMAJANG',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '125',
                'name' => 'Madiun',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '126',
                'name' => 'Magelang',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '127',
                'name' => 'Magetan',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '128',
                'name' => 'Majalengka',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '129',
                'name' => 'Makasar',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '130',
                'name' => 'Malang',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '131',
                'name' => 'Malang Kota',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '132',
                'name' => 'Malinau',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '133',
                'name' => 'MALINGPING',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '134',
                'name' => 'Manado',
                'province_id' => '28',
                'created_by' => '1',
            ],
            [
                'id' => '135',
                'name' => 'Manokwari',
                'province_id' => '29',
                'created_by' => '1',
            ],
            [
                'id' => '136',
                'name' => 'Masohi',
                'province_id' => '3',
                'created_by' => '1',
            ],
            [
                'id' => '137',
                'name' => 'MATARAM',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '138',
                'name' => 'Medan',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '139',
                'name' => 'Medan Timur',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '140',
                'name' => 'MELAWI',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '141',
                'name' => 'MEMPAWAH',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '142',
                'name' => 'MERANGIN (BANGKO)',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '143',
                'name' => 'METRO',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '144',
                'name' => 'MEULABOH',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '145',
                'name' => 'MEUREUDU',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '146',
                'name' => 'Mojokerto',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '147',
                'name' => 'MUARA BUNGO',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '148',
                'name' => 'Muara enim',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '149',
                'name' => 'MUARA TEBO',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '150',
                'name' => 'Muaraenim',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '151',
                'name' => 'MUARO JAMBI',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '152',
                'name' => 'Musi Banyu Asin',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '153',
                'name' => 'Nagan Raya',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '154',
                'name' => 'Nganjuk',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '155',
                'name' => 'Ngawi',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '156',
                'name' => 'Nias',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '158',
                'name' => 'Ogan komering Ulu',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '159',
                'name' => 'Ogan komering Ulu Selatan',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '160',
                'name' => 'Ogan komering Ulu Timur',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '161',
                'name' => 'Ogan Ilir',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '162',
                'name' => 'Ogan Komering Ilir',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '163',
                'name' => 'Pacitan',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '164',
                'name' => 'Padang',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '165',
                'name' => 'Padang Lawas Utara',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '166',
                'name' => 'Padang Panjang',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '167',
                'name' => 'Padang Sidempuan',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '168',
                'name' => 'Pagaralam',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '169',
                'name' => 'Palembang',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '170',
                'name' => 'Palu',
                'province_id' => '30',
                'created_by' => '1',
            ],
            [
                'id' => '171',
                'name' => 'Pamekasan',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '172',
                'name' => 'Pandeglang',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '173',
                'name' => 'Pangandaran',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '174',
                'name' => 'Pangkal Pinang',
                'province_id' => '7',
                'created_by' => '1',
            ],
            [
                'id' => '175',
                'name' => 'Pasaman Barat',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '176',
                'name' => 'Pasuruan',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '177',
                'name' => 'Pati',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '178',
                'name' => 'Payakumbuh',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '179',
                'name' => 'Pekalongan',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '180',
                'name' => 'Pekanbaru',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '181',
                'name' => 'Pemalang',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '182',
                'name' => 'Pematang Siantar',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '183',
                'name' => 'PERAWANG',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '184',
                'name' => 'PESAWARAN',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '185',
                'name' => 'Pesisir Selatan',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '186',
                'name' => 'Pidie',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '187',
                'name' => 'Pohwuato',
                'province_id' => '19',
                'created_by' => '1',
            ],
            [
                'id' => '188',
                'name' => 'Ponorogo',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '189',
                'name' => 'PONTIANAK',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '190',
                'name' => 'Prabumulih',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '191',
                'name' => 'PRINGSEWU',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '192',
                'name' => 'PROBOLINGGO',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '193',
                'name' => 'PURBALINGGA',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '194',
                'name' => 'Purwakarta',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '195',
                'name' => 'PURWOKERTO',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '196',
                'name' => 'Purworejo',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '197',
                'name' => 'RANGKAS BITUNG',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '198',
                'name' => 'Rantauprapat, Labuhanbatu',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '199',
                'name' => 'Rejang Lebong',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '200',
                'name' => 'Rembang',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '201',
                'name' => 'Rengat',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '202',
                'name' => 'Rokan Hilir',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '203',
                'name' => 'Samarinda',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '204',
                'name' => 'SAMBAS',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '205',
                'name' => 'Sampang',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '206',
                'name' => 'Sangata',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '207',
                'name' => 'SANGGAU',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '208',
                'name' => 'SAROLANGUN',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '209',
                'name' => 'Sawah Lunto',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '210',
                'name' => 'Sei Piring, Kab.Asahan Perbatasan Kab. Labuhanbatu',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '211',
                'name' => 'SEKADAU',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '212',
                'name' => 'Semarang',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '213',
                'name' => 'Serang',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '214',
                'name' => 'Serdang Bedagai',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '215',
                'name' => 'Siak',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '216',
                'name' => 'Sibolga',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '217',
                'name' => 'Sidoarjo',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '218',
                'name' => 'Sijunjung',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '219',
                'name' => 'SINGKAWANG',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '220',
                'name' => 'SINTANG',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '221',
                'name' => 'SITUBONDO',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '222',
                'name' => 'Sleman',
                'province_id' => '12',
                'created_by' => '1',
            ],
            [
                'id' => '223',
                'name' => 'Solo',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '224',
                'name' => 'Solok',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '225',
                'name' => 'Sorong',
                'province_id' => '29',
                'created_by' => '1',
            ],
            [
                'id' => '226',
                'name' => 'SRAGEN',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '227',
                'name' => 'Subang',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '228',
                'name' => 'Sukabumi',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '229',
                'name' => 'SUKOHARJO',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '230',
                'name' => 'SUMBAWA',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '231',
                'name' => 'SUMBAWA BARAT',
                'province_id' => '18',
                'created_by' => '1',
            ],
            [
                'id' => '232',
                'name' => 'Sumedang',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '233',
                'name' => 'Sumenep',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '234',
                'name' => 'Surabaya',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '235',
                'name' => 'Surabaya Utara',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '236',
                'name' => 'TABANAN',
                'province_id' => '4',
                'created_by' => '1',
            ],
            [
                'id' => '237',
                'name' => 'TAKENGON',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '238',
                'name' => 'Tangerang',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '239',
                'name' => 'TANGERANG SELATAN',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '240',
                'name' => 'TANGGAMUS',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '241',
                'name' => 'TANJUNG BALAI KARIMUN',
                'province_id' => '13',
                'created_by' => '1',
            ],
            [
                'id' => '242',
                'name' => 'TANJUNG JABUNG BARAT',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '243',
                'name' => 'TANJUNG JABUNG TIMUR',
                'province_id' => '14',
                'created_by' => '1',
            ],
            [
                'id' => '244',
                'name' => 'TANJUNG PINANG',
                'province_id' => '13',
                'created_by' => '1',
            ],
            [
                'id' => '245',
                'name' => 'Tanjung Selor',
                'province_id' => '31',
                'created_by' => '1',
            ],
            [
                'id' => '246',
                'name' => 'TAPAK TUAN',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '247',
                'name' => 'Tapanuli Selatan',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '248',
                'name' => 'Tarakan',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '249',
                'name' => 'Tasikmalaya',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '250',
                'name' => 'Tebing Tinggi',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '251',
                'name' => 'Tegal',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '252',
                'name' => 'Temanggung',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '253',
                'name' => 'Tenggarong',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '254',
                'name' => 'Trenggalek',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '255',
                'name' => 'Tuban',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '256',
                'name' => 'TULANG BAWANG',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '257',
                'name' => 'Tulungagung',
                'province_id' => '8',
                'created_by' => '1',
            ],
            [
                'id' => '258',
                'name' => 'UJUNG BATU',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '259',
                'name' => 'Ukui Sorek',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '260',
                'name' => 'WAY KANAN',
                'province_id' => '26',
                'created_by' => '1',
            ],
            [
                'id' => '261',
                'name' => 'WONOGIRI',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '262',
                'name' => 'Wonosobo',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '263',
                'name' => 'Yogya',
                'province_id' => '12',
                'created_by' => '1',
            ],
            [
                'id' => '264',
                'name' => 'Cilacap',
                'province_id' => '6',
                'created_by' => '1',
            ],
            [
                'id' => '265',
                'name' => 'PANGKEP',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '266',
                'name' => 'BOLAANG MONGONDOW',
                'province_id' => '28',
                'created_by' => '1',
            ],
            [
                'id' => '267',
                'name' => 'MAROS',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '268',
                'name' => 'JENEPONTO',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '269',
                'name' => 'PARIGI MOUTONG',
                'province_id' => '30',
                'created_by' => '1',
            ],
            [
                'id' => '270',
                'name' => 'TERNATE',
                'province_id' => '33',
                'created_by' => '1',
            ],
            [
                'id' => '271',
                'name' => 'GOWA',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '272',
                'name' => 'DEMAK',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '273',
                'name' => 'KAPUAS',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '274',
                'name' => 'KENDAL',
                'province_id' => '11',
                'created_by' => '1',
            ],
            [
                'id' => '275',
                'name' => 'SIDRAP',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '276',
                'name' => 'LEBAK',
                'province_id' => '20',
                'created_by' => '1',
            ],
            [
                'id' => '277',
                'name' => 'SOPPENG',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '278',
                'name' => 'TAKALAR',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '279',
                'name' => 'PALOPO',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '280',
                'name' => 'BULUKUMBA',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '281',
                'name' => 'PAREPARE',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '282',
                'name' => 'MINAHASA',
                'province_id' => '28',
                'created_by' => '1',
            ],
            [
                'id' => '283',
                'name' => 'INDRAGIRI HILIR',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '284',
                'name' => 'BITUNG',
                'province_id' => '28',
                'created_by' => '1',
            ],
            [
                'id' => '285',
                'name' => 'LUWU',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '286',
                'name' => 'SUBULUSSALAM',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '287',
                'name' => 'BANJARBARU',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '288',
                'name' => 'MUNA',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '289',
                'name' => 'ENREKANG',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '290',
                'name' => '-',
                'province_id' => '35',
                'created_by' => '1',
            ],
            [
                'id' => '291',
                'name' => 'BOMBANA',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '292',
                'name' => 'BARITO',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '293',
                'name' => 'MOROWALI',
                'province_id' => '30',
                'created_by' => '1',
            ],
            [
                'id' => '294',
                'name' => 'BUOL',
                'province_id' => '30',
                'created_by' => '1',
            ],
            [
                'id' => '295',
                'name' => 'MANDAILING NATAL',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '296',
                'name' => 'TOJO UNA-UNA',
                'province_id' => '30',
                'created_by' => '1',
            ],
            [
                'id' => '297',
                'name' => 'ROKAN HULU',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '298',
                'name' => 'MERAUKE',
                'province_id' => '22',
                'created_by' => '1',
            ],
            [
                'id' => '299',
                'name' => 'PALANGKA RAYA',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '300',
                'name' => 'GORONTALO UTARA',
                'province_id' => '19',
                'created_by' => '1',
            ],
            [
                'id' => '301',
                'name' => 'KUANTAN SINGINGI',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '302',
                'name' => 'TAPIN',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '303',
                'name' => 'KATINGAN',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '304',
                'name' => 'KOLAKA UTARA',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '305',
                'name' => 'GAYO LUES',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '306',
                'name' => 'KONAWE SELATAN',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '307',
                'name' => 'TIMOR TENGAH SELATAN',
                'province_id' => '25',
                'created_by' => '1',
            ],
            [
                'id' => '308',
                'name' => 'BANJAR',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '309',
                'name' => 'BONE',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '310',
                'name' => 'MUSI RAWAS UTARA',
                'province_id' => '24',
                'created_by' => '1',
            ],
            [
                'id' => '311',
                'name' => 'KAPUAS HULU',
                'province_id' => '16',
                'created_by' => '1',
            ],
            [
                'id' => '312',
                'name' => 'LEBONG',
                'province_id' => '17',
                'created_by' => '1',
            ],
            [
                'id' => '313',
                'name' => 'PELALAWAN',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '314',
                'name' => 'SINJAI',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '315',
                'name' => 'TOMOHON',
                'province_id' => '28',
                'created_by' => '1',
            ],
            [
                'id' => '316',
                'name' => 'TUAL',
                'province_id' => '3',
                'created_by' => '1',
            ],
            [
                'id' => '318',
                'name' => 'PULANG PISAU',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '319',
                'name' => 'TIMOR TENGAH UTARA',
                'province_id' => '25',
                'created_by' => '1',
            ],
            [
                'id' => '320',
                'name' => 'ACEH TENGGARA',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '321',
                'name' => 'TANIMBAR',
                'province_id' => '3',
                'created_by' => '1',
            ],
            [
                'id' => '322',
                'name' => 'KUALA PEMBUANG II',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '323',
                'name' => 'PINRANG',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '324',
                'name' => 'MIMIKA',
                'province_id' => '22',
                'created_by' => '1',
            ],
            [
                'id' => '325',
                'name' => 'BUTON',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '326',
                'name' => 'MANGGARAI BARAT',
                'province_id' => '25',
                'created_by' => '1',
            ],
            [
                'id' => '327',
                'name' => 'BENGKULU UTARA',
                'province_id' => '17',
                'created_by' => '1',
            ],
            [
                'id' => '328',
                'name' => 'KOTA KOTAMOBAGU',
                'province_id' => '28',
                'created_by' => '1',
            ],
            [
                'id' => '329',
                'name' => 'BARRU',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '330',
                'name' => 'LIMA PULUH',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '331',
                'name' => 'SUKAMARA',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '332',
                'name' => 'KOTAWARINGIN BARAT',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '333',
                'name' => 'PADANG PARIAMAN',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '335',
                'name' => 'BARITO TIMUR',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '336',
                'name' => 'HULU SUNGAI SELATAN',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '337',
                'name' => 'KUTAI TIMUR',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '338',
                'name' => 'MAMUJU',
                'province_id' => '34',
                'created_by' => '1',
            ],
            [
                'id' => '339',
                'name' => 'BELU',
                'province_id' => '25',
                'created_by' => '1',
            ],
            [
                'id' => '340',
                'name' => 'KUTAI KARTANEGARA',
                'province_id' => '5',
                'created_by' => '1',
            ],
            [
                'id' => '341',
                'name' => 'TABALONG',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '342',
                'name' => 'KOLAKA',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '343',
                'name' => 'KEPAHIANG',
                'province_id' => '17',
                'created_by' => '1',
            ],
            [
                'id' => '344',
                'name' => 'TANJUNGBALAI',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '345',
                'name' => 'TAPANULI UTARA',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '346',
                'name' => 'LANGSA',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '347',
                'name' => 'PANGKAJENE',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '348',
                'name' => 'BELITUNG TIMUR',
                'province_id' => '7',
                'created_by' => '1',
            ],
            [
                'id' => '349',
                'name' => 'TANAH DATAR',
                'province_id' => '2',
                'created_by' => '1',
            ],
            [
                'id' => '350',
                'name' => 'TORAJA UTARA',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '351',
                'name' => 'KEEROM',
                'province_id' => '22',
                'created_by' => '1',
            ],
            [
                'id' => '352',
                'name' => 'ASAHAN',
                'province_id' => '15',
                'created_by' => '1',
            ],
            [
                'id' => '353',
                'name' => 'ACEH UTARA',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '354',
                'name' => 'POLEWALI MANDAR',
                'province_id' => '34',
                'created_by' => '1',
            ],
            [
                'id' => '355',
                'name' => 'BARITO UTARA',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '356',
                'name' => 'TANAH BUMBU',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '357',
                'name' => 'DUMAI',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '358',
                'name' => 'ACEH TIMUR',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '359',
                'name' => 'HALMAHERA UTARA',
                'province_id' => '33',
                'created_by' => '1',
            ],
            [
                'id' => '360',
                'name' => 'BALANGAN',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '361',
                'name' => 'HALMAHERA TIMUR',
                'province_id' => '33',
                'created_by' => '1',
            ],
            [
                'id' => '362',
                'name' => 'WAROPEN',
                'province_id' => '22',
                'created_by' => '1',
            ],
            [
                'id' => '363',
                'name' => 'BANGGAI',
                'province_id' => '30',
                'created_by' => '1',
            ],
            [
                'id' => '365',
                'name' => 'SERUYAN',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '366',
                'name' => 'TANAH LAUT',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '367',
                'name' => 'INDRAGIRI HULU',
                'province_id' => '9',
                'created_by' => '1',
            ],
            [
                'id' => '368',
                'name' => 'MANGGARAI',
                'province_id' => '25',
                'created_by' => '1',
            ],
            [
                'id' => '369',
                'name' => 'TANA TORAJA',
                'province_id' => '27',
                'created_by' => '1',
            ],
            [
                'id' => '370',
                'name' => 'KOTAWARINGIN TIMUR',
                'province_id' => '32',
                'created_by' => '1',
            ],
            [
                'id' => '371',
                'name' => 'BURU',
                'province_id' => '3',
                'created_by' => '1',
            ],
            [
                'id' => '372',
                'name' => 'KAUR',
                'province_id' => '17',
                'created_by' => '1',
            ],
            [
                'id' => '373',
                'name' => 'ACEH TAMIANG',
                'province_id' => '1',
                'created_by' => '1',
            ],
            [
                'id' => '374',
                'name' => 'HULU SUNGAI UTARA',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '375',
                'name' => 'HULU SUNGAI TENGAH',
                'province_id' => '10',
                'created_by' => '1',
            ],
            [
                'id' => '376',
                'name' => 'SIKKA',
                'province_id' => '25',
                'created_by' => '1',
            ],
            [
                'id' => '377',
                'name' => 'BAUBAU',
                'province_id' => '23',
                'created_by' => '1',
            ],
            [
                'id' => '378',
                'name' => 'ACEH BARAT',
                'province_id' => '1',
                'created_by' => '1',
            ],
        ];

        $table->insert($data)->save();
    }
}
